### ISSUE TITLE
Предложение по доработке тренажера хираганы, катаканы и набору слов

### ISSUE THREAD

**Issue by digitalstars** [ivacuum/hosting#16]
1) Возможность выбирать не только столбцы, но и отдельные слоги из разных столбцов
2) Убрать повторы выдаваемых слогов. Например, если я выбираю 2 столбца, то используется 10 слогов. 10 элементов массива, после того как тренажер выдал слог, удалять его из массива. Когда закончатся все - обновить массив снова до 10 слогов.
3) Также к этому можно добавить алгоритм для учета ошибок. Если из 10 слогов пользователь чаще всего ошибается в 2-х, то их надо показывать чаще, чем те, в которых пользователь вообще не ошибается. По какой-нить условной формуле:
 (сколько_раз_показан_этот_слог / количество_правильных_ответов), и столько раз добавить этот слог в следующую итерацию.
 Например по статистике, слог был отвечен правильно только 5/20, по формуле получаем 4 - и 4 раза этот слог добавляем к итерации с 10 дефолтными.
 
Статистику можно хранить в браузере, чтобы не терять при перезаходе и учитывать только последние 30 ответов для каждого слога. Думаю такой подходит сможет немного ускорить обучение изучающим.

**Comment by digitalstars** [comment]
4) И еще было бы классно добавить к выводу написанных слов транскрипцию хираганой и перевод на русский язык
![изображение](https://user-images.githubusercontent.com/46852707/147571894-a550bb39-5179-4d9f-8cac-8c6e738f6afb.png)

**Comment by ivacuum** [comment]
Спасибо за пожелания, некоторые прокомментирую.

> убрать повторы выдаваемых слогов

Неоднозначная штука, потому что тогда в силу вступит наше умение указывать ответ методом исключения — особенно это будет заметно как раз на маленьких выборках.

> алгоритм для учета ошибок

Не готов так усложнять тренажер. Постепенно уменьшаю количество js-элементов на сайте, тренажер азбук — один из последних остался. Три новых тренажера делал уже преимущественно на серверной стороне, так как это больше вдохновляет и больше мой профиль. Так что дальнейшее добавление функционала сюда выглядит маловероятным. Тем более я не освоил автотесты фронтэнда (их сейчас нет), поэтому правки вызывают высокий риск что-то рабочее поломать

> транскрипция написанных слов хираганой

Посмотрю смогу ли органично вписать хирагану, спасибо. На русский перевести не осилю, потому что слов много тысяч, вариантов перевода может быть несколко, как на скрине, а база первоисточника периодически модифицируется, то есть переводы потребуется актуализировать несколько раз в месяц для некоторых слов.

Меня больше недавно поразило, что тренажер слов не работал на ряде андроидов в хроме — банально enter на клавиатуре не работал. И ни одного отзыва об этом не было! Благо теперь это поправлено.

**Comment by digitalstars** [comment]
Насчет повторов - просто заметил особенность, что один слог может выдать 10 раз из 120 попыток, но при этом другой не выдать ни разу. И это плохо для ситуаций, когда зашел повторить минут на 10, но за 120 попыток тебе не по ~3 раза каждый слог выдало, а как попало. Возможно какой-то косяк в рандомизации в текущей реализации.

Также перенос на сервер уничтожит одну особенность тренажера - возможность использовать его оффлайн. Лично мне это пригодилось, когда 3 часа ехал между городами без интернета и тыкался в тренажер :)

Но в любом случае спасибо

**Comment by digitalstars** [comment]
И еще в тренажере хангыля почему-то нельзя открывать подсказку используя пробел (или какую-то горячую клавишу), это неудобно

**Comment by ivacuum** [comment]
Реализация рандома самая стандартная используется:
https://github.com/lodash/lodash/blob/master/random.js#L70
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/random#getting_a_random_integer_between_two_values

Пока не готов с рандомом бороться. Может либо при обновлении фронта вроде vue 2 до vue 3, либо перед следующей поездкой в Японию, но таковой пока нет в планах — только Корея послезавтра. Сожалею, что подгорает с рандома. Повтор сейчас убирается только последней загадки — чтобы следующий загаданный слог отличался от текущего.

Да, это приятная фича с оффлайном, в частности именно из-за нее я отказался от идеи перенести реализацию на сервер. А остальные тренажеры уже сделаны на сервере.

Вот бета-версия тренажера чисел. Корейские числа не удавалось три года никак запомнить, а с ним двадцать минут ушло на запоминание счета до тысячи
https://vacuum.name/trainers/numbers

Спасибо, пробел теперь показывает ответ в тренажере хангыля ✔️
